### ISSUE TITLE
老大IOS13系统无法保存ipa怎么办

### ISSUE THREAD

**Issue by ningQAQ** [SmileZXLee/IpaDownloadTool#1]
提示一串英文 就是保存不了

**Comment by SmileZXLee** [comment]
您好，方便提供一下具体的下载页面链接吗，应该是下载页面导致的，我这边使用iOS13测试是正常的。

> 提示一串英文 就是保存不了

**Comment by ningQAQ** [comment]
> 您好，方便提供一下具体的下载页面链接吗，应该是下载页面导致的，我这边使用iOS13测试是正常的。
> 
> > 提示一串英文 就是保存不了

所有的ipa下载链接都保存不了，我的是iphone11Pro 13.1.2系统 我给你发一张图

**Comment by ningQAQ** [comment]
我的XR升级到ios13.1.2系统 也提示这种情况 所有的ipa都保存不了  可以下载 但是一保存就会底下就会出现英文 请大佬修复一下 谢谢了

**Comment by ningQAQ** [comment]
我也不知道这是不是系统问题 没有其他系统去测试了

**Comment by ningQAQ** [comment]
我发现一个问题 自签可以保存 但是如果开发者账号或者企业签名 就会提示保存不了 希望大佬看一下 我刚刚发现的

**Comment by SmileZXLee** [comment]
> 我发现一个问题 自签可以保存 但是如果开发者账号或者企业签名 就会提示保存不了 希望大佬看一下 我刚刚发现的

中午的时候刚刚把系统升级至13.2.2，发现还是正常的。保存不了是可以下载完毕后无法分享吗，还是无法获取ipa下载链接、还是无法下载呢

**Comment by ningQAQ** [comment]
> > 我发现一个问题 自签可以保存 但是如果开发者账号或者企业签名 就会提示保存不了 希望大佬看一下 我刚刚发现的
> 
> 中午的时候刚刚把系统升级至13.2.2，发现还是正常的。保存不了是可以下载完毕后无法分享吗，还是无法获取ipa下载链接、还是无法下载呢

可以下载完毕 但是刚刚好下载完以后 底部就出现"CFNEtworkDownload_lzb81w.tmp" couldn't be moved because you don't permission to access....这个东西  就是无法保存ipa分享

**Comment by ningQAQ** [comment]
就是保存不了 无法分享

**Comment by ningQAQ** [comment]
如果用大佬的源码自己xcode 然后个人免费7天证书安装在手机上就没问题   但是如果其他开发者或者企业签名 就会出现这个问题

**Comment by ningQAQ** [comment]
我刚刚让我身边的人安装了 他们都是13系统 都会提示这个英文 无法保存ipa  看来真的是系统的原因

**Comment by SmileZXLee** [comment]
> 我刚刚让我身边的人安装了 他们都是13系统 都会提示这个英文 无法保存ipa 看来真的是系统的原因

应该是文件路径的问题，我修改了github上面的项目，将toast更改为弹窗了，以便能看到完整的错误路径信息，麻烦您更新一下然后运行在手机上，然后把错误弹窗的页面发给我一下，谢谢啦

**Comment by ningQAQ** [comment]
> github

貌似不能发送图片 大佬可以加个qq吗

**Comment by ningQAQ** [comment]
- ``

**Comment by ningQAQ** [comment]
我的qq 480168030

**Comment by ningQAQ** [comment]
> > 我刚刚让我身边的人安装了 他们都是13系统 都会提示这个英文 无法保存ipa 看来真的是系统的原因
> 
> 应该是文件路径的问题，我修改了github上面的项目，将toast更改为弹窗了，以便能看到完整的错误路径信息，麻烦您更新一下然后运行在手机上，然后把错误弹窗的页面发给我一下，谢谢啦

大佬 加个qq  我发错误图片你   480168030
